const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');const $=id=>document.getElementById(id);const menu=$('menu'),game=$('gameScreen'),pause=$('pause'),story=$('story');const keys={},touchJump={value:false};let state='menu',level=1,score=0;
const lore=`Há muito tempo, a pequena Rainha guardava uma coroa que não era apenas um símbolo. Ela mantinha o equilíbrio entre os lugares do reino. Certa manhã, a coroa desapareceu. Desde então, caminhos mudaram, criaturas estranhas apareceram e partes do reino ficaram isoladas. Agora começa uma jornada por um mundo pequeno para quem vive nele — mas gigantesco para quem se aventura por suas trilhas.`;
const phases=[{name:'Jardim da Rainha',goal:'Encontre 4 fragmentos da coroa',width:4200},{name:'Bosque dos Cogumelos',goal:'Atravesse o bosque e encontre a saída',width:4800},{name:'Vila dos Pequenos',goal:'Ajude os moradores e descubra a pista',width:3600}];
function showInfo(t){$('info').innerHTML=t;$('info').classList.remove('hidden')}$('startBtn').onclick=()=>startNew();$('continueBtn').onclick=()=>startNew();$('loreBtn').onclick=()=>showInfo('<b>Lore</b><br>'+lore);$('howBtn').onclick=()=>showInfo('<b>Como jogar</b><br>Ande com A/D ou ←/→. Pule com Espaço, W ou ⬆. Derrote inimigos pulando sobre eles. Colete objetivos, use checkpoints e chegue ao final da fase.');$('pauseBtn').onclick=()=>togglePause();$('resumeBtn').onclick=()=>togglePause();$('restartBtn').onclick=()=>{pause.classList.add('hidden');resetLevel()};$('menuBtn').onclick=()=>{pause.classList.add('hidden');location.href='campaign.html'};
function startNew(){level=Number(new URLSearchParams(location.search).get('level'))||1;score=0;game.classList.remove('hidden');state='play';resetLevel();storyIntro()}
function storyIntro(){story.classList.remove('hidden');state='story';$('storyText').innerHTML='<h2>O começo</h2><p>'+lore.split('. ')[0]+'.</p><p>Uma pista aponta para o Jardim da Rainha.</p>';$('storyNext').onclick=()=>{story.classList.add('hidden');state='play'}}
$('storyNext').onclick=()=>{story.classList.add('hidden');state='play'};
function togglePause(){if(state==='play'){state='pause';pause.classList.remove('hidden')}else if(state==='pause'){state='play';pause.classList.add('hidden')}}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='escape'){togglePause();return}keys[k]=true;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
let world={width:4200},player,enemies,platforms,collectibles,checkpoint;
function resetLevel(){const p=phases[level-1];world.width=p.width;player={x:90,y:390,w:34,h:44,vx:0,vy:0,ground:false,health:3,inv:0,spawnX:90,spawnY:390};platforms=[{x:0,y:480,w:700,h:60},{x:760,y:440,w:280,h:18},{x:1110,y:380,w:230,h:18},{x:1430,y:450,w:330,h:18},{x:1850,y:390,w:260,h:18},{x:2200,y:330,w:300,h:18},{x:2620,y:430,w:360,h:18},{x:3100,y:360,w:420,h:18},{x:3500,y:480,w:300,h:60},{x:3900,y:420,w:300,h:18}];enemies=[{x:520,y:444,w:34,h:36,vx:55,a:430,b:650,alive:true},{x:1240,y:344,w:34,h:36,vx:65,a:1120,b:1310,alive:true},{x:2020,y:354,w:34,h:36,vx:60,a:1860,b:2070,alive:true},{x:2730,y:394,w:34,h:36,vx:75,a:2640,b:2920,alive:true},{x:3260,y:324,w:34,h:36,vx:80,a:3120,b:3450,alive:true}];collectibles=[{x:920,y:395},{x:1530,y:405},{x:2320,y:285},{x:3210,y:315}].map((x,i)=>({...x,i,taken:false}));checkpoint={x:1850,active:false};$('phaseTitle').textContent=p.name;$('objective').textContent=p.goal}
function update(dt){if(state!=='play')return;const left=keys.arrowleft||keys.a,right=keys.arrowright||keys.d;player.vx=(right?240:0)-(left?240:0);if((keys[' ']||keys.arrowup||keys.w||touchJump.value)&&player.ground){player.vy=-570;player.ground=false;touchJump.value=false}player.vy+=1550*dt;const oldBottom=player.y+player.h;player.x+=player.vx*dt;player.y+=player.vy*dt;player.ground=false;for(const p of platforms){const b=player.y+player.h;if(player.x+player.w>p.x&&player.x<p.x+p.w&&oldBottom<=p.y&&b>=p.y&&player.vy>=0){player.y=p.y-player.h;player.vy=0;player.ground=true}}player.x=Math.max(0,Math.min(world.width-player.w,player.x));player.inv=Math.max(0,player.inv-dt);if(player.x>checkpoint.x)checkpoint.active=true;if(checkpoint.active){player.spawnX=checkpoint.x;player.spawnY=340}if(player.y>canvas.height+160)damage(true);
for(const e of enemies){if(!e.alive)continue;e.x+=e.vx*dt;if(e.x<e.a||e.x>e.b)e.vx*=-1;if(player.inv<=0&&player.x+player.w>e.x&&player.x<e.x+e.w&&player.y+player.h>e.y&&player.y<e.y+e.h){if(player.vy>100&&player.y+player.h-e.y<24){e.alive=false;player.vy=-360;score+=100}else damage(false)}}collectibles.forEach(c=>{if(!c.taken&&player.x<c.x+28&&player.x+player.w>c.x&&player.y<c.y+28&&player.y+player.h>c.y){c.taken=true;score+=25}});if(level===1&&collectibles.every(c=>c.taken)&&player.x>3850)finishLevel()}
function damage(fall){if(player.inv>0)return;player.health--;player.inv=1.3;if(player.health<=0){resetLevel();return}player.x=player.spawnX;player.y=player.spawnY;player.vx=0;player.vy=0}
function finishLevel(){if(level<phases.length){state='story';story.classList.remove('hidden');$('storyText').innerHTML='<h2>Fase concluída!</h2><p>Você avançou na busca pela Coroa Real.</p><p><b>'+phases[level].name+'</b> espera por você.</p>';$('storyNext').onclick=()=>{story.classList.add('hidden');level++;location.href='campaign.html';state='play'}}else{state='story';story.classList.remove('hidden');$('storyText').innerHTML='<h2>Prólogo concluído 👑</h2><p>A primeira jornada terminou. A pista aponta para além do reino conhecido.</p><p>Esse é o fim do protótipo narrativo.</p>';$('storyNext').onclick=()=>{story.classList.add('hidden');game.classList.add('hidden');menu.classList.remove('hidden');state='menu'}}}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);const cam=Math.max(0,Math.min(world.width-canvas.width,player.x-canvas.width*.38));ctx.save();ctx.translate(-cam,0);const g=ctx.createLinearGradient(0,0,0,canvas.height);g.addColorStop(0,'#9fd9e9');g.addColorStop(1,'#e2f3bd');ctx.fillStyle=g;ctx.fillRect(cam,0,canvas.width,canvas.height);for(let x=0;x<world.width;x+=280){ctx.fillStyle='#79b96a';ctx.beginPath();ctx.arc(x+130,500,150,Math.PI,0);ctx.fill()}for(const p of platforms){ctx.fillStyle='#8b603c';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#63a84f';ctx.fillRect(p.x,p.y-8,p.w,10)}for(const e of enemies)if(e.alive){ctx.fillStyle='#7c4f8f';ctx.beginPath();ctx.arc(e.x+17,e.y+18,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(e.x+7,e.y+10,7,7);ctx.fillRect(e.x+20,e.y+10,7,7)}collectibles.forEach(c=>{if(!c.taken){ctx.font='30px sans-serif';ctx.fillText('👑',c.x,c.y+27)}});if(checkpoint.active){ctx.fillStyle='#f4d46b';ctx.fillRect(checkpoint.x,300,6,140);ctx.font='25px sans-serif';ctx.fillText('🚩',checkpoint.x-12,300)}ctx.globalAlpha=player.inv>0?.5:1;ctx.fillStyle='#f1c56d';ctx.fillRect(player.x,player.y,player.w,player.h);ctx.fillStyle='#5a3828';ctx.fillRect(player.x+5,player.y+8,7,7);ctx.fillRect(player.x+22,player.y+8,7,7);ctx.restore();ctx.fillStyle='#29452b';ctx.font='17px sans-serif';ctx.fillText('👑 '+score+'   ❤️ '+player.health+'   Fragmentos: '+collectibles.filter(c=>c.taken).length+'/'+collectibles.length,18,28)}
document.querySelectorAll('.touch-controls button').forEach(btn=>{const key=btn.dataset.key;const press=e=>{e.preventDefault();if(key==='jump')touchJump.value=true;else keys[key]=true;btn.setPointerCapture?.(e.pointerId)};const release=e=>{e.preventDefault();if(key!=='jump')keys[key]=false};btn.addEventListener('pointerdown',press);['pointerup','pointercancel','pointerleave'].forEach(ev=>btn.addEventListener(ev,release))});
let last=performance.now();function loop(now){const dt=Math.min((now-last)/1000,.033);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);