const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');const menu=document.getElementById('menu'),gameScreen=document.getElementById('gameScreen');document.getElementById('startBtn').onclick=()=>{menu.classList.add('hidden');gameScreen.classList.remove('hidden')};document.getElementById('howBtn').onclick=()=>document.getElementById('howTo').classList.toggle('hidden');
const keys={},touchJump={value:false};addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
const world={width:3600},player={x:90,y:390,w:34,h:44,vx:0,vy:0,ground:false,health:3,inv:0};const platforms=[{x:0,y:480,w:700,h:60},{x:760,y:440,w:280,h:18},{x:1110,y:380,w:230,h:18},{x:1430,y:450,w:330,h:18},{x:1850,y:390,w:260,h:18},{x:2200,y:330,w:300,h:18},{x:2620,y:430,w:360,h:18},{x:3100,y:360,w:420,h:18},{x:3500,y:480,w:100,h:60}];
const enemies=[{x:520,y:444,w:34,h:36,vx:55,start:450,end:650,alive:true},{x:1240,y:344,w:34,h:36,vx:65,start:1120,end:1310,alive:true},{x:2020,y:354,w:34,h:36,vx:60,start:1860,end:2070,alive:true},{x:2730,y:394,w:34,h:36,vx:75,start:2640,end:2920,alive:true}];
const crowns=[{x:920,y:395},{x:1530,y:405},{x:2320,y:285},{x:3210,y:315}],collected=new Set();
function reset(){player.x=90;player.y=390;player.vy=0;player.health=3;player.inv=0;enemies.forEach(e=>e.alive=true);collected.clear()}
function jumpPressed(){return keys[' ']||keys['arrowup']||keys['w']||touchJump.value}
function update(dt){const left=keys['arrowleft']||keys['a'],right=keys['arrowright']||keys['d'];player.vx=(right?240:0)-(left?240:0);if(jumpPressed()&&player.ground){player.vy=-570;player.ground=false;touchJump.value=false}player.vy+=1550*dt;const oldBottom=player.y+player.h;player.x+=player.vx*dt;player.y+=player.vy*dt;player.ground=false;
for(const p of platforms){const b=player.y+player.h;if(player.x+player.w>p.x&&player.x<p.x+p.w&&oldBottom<=p.y&&b>=p.y&&player.vy>=0){player.y=p.y-player.h;player.vy=0;player.ground=true}}
player.x=Math.max(0,Math.min(world.width-player.w,player.x));player.inv=Math.max(0,player.inv-dt);
if(player.y>canvas.height+200){player.x=90;player.y=390;player.vy=0;player.health--}
for(const e of enemies){if(!e.alive)continue;e.x+=e.vx*dt;if(e.x<e.start||e.x>e.end)e.vx*=-1;if(player.inv<=0&&player.x+player.w>e.x&&player.x<e.x+e.w&&player.y+player.h>e.y&&player.y<e.y+e.h){if(player.vy>100&&player.y+player.h-e.y<22){e.alive=false;player.vy=-360}else{player.health--;player.inv=1.2;player.vx=player.x<e.x?-260:260;player.vy=-280}}}
crowns.forEach((c,i)=>{if(!collected.has(i)&&player.x<c.x+28&&player.x+player.w>c.x&&player.y<c.y+28&&player.y+player.h>c.y)collected.add(i)});
if(player.health<=0){reset()}}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);const camera=Math.max(0,Math.min(world.width-canvas.width,player.x-canvas.width*.38));ctx.save();ctx.translate(-camera,0);const g=ctx.createLinearGradient(0,0,0,canvas.height);g.addColorStop(0,'#9fd9e9');g.addColorStop(1,'#e2f3bd');ctx.fillStyle=g;ctx.fillRect(camera,0,canvas.width,canvas.height);
for(let x=0;x<world.width;x+=280){ctx.fillStyle='#79b96a';ctx.beginPath();ctx.arc(x+130,500,150,Math.PI,0);ctx.fill()}for(const p of platforms){ctx.fillStyle='#8b603c';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#63a84f';ctx.fillRect(p.x,p.y-8,p.w,10)}
for(const e of enemies)if(e.alive){ctx.fillStyle='#7c4f8f';ctx.beginPath();ctx.arc(e.x+17,e.y+18,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(e.x+7,e.y+10,7,7);ctx.fillRect(e.x+20,e.y+10,7,7)}
crowns.forEach((c,i)=>{if(!collected.has(i)){ctx.font='30px sans-serif';ctx.fillText('👑',c.x,c.y+27)}})
ctx.globalAlpha=player.inv>0?.5:1;ctx.fillStyle='#f1c56d';ctx.fillRect(player.x,player.y,player.w,player.h);ctx.fillStyle='#5a3828';ctx.fillRect(player.x+5,player.y+8,7,7);ctx.fillRect(player.x+22,player.y+8,7,7);ctx.globalAlpha=1;ctx.restore();
ctx.fillStyle='#29452b';ctx.font='18px sans-serif';ctx.fillText('Coroas: '+collected.size+'/'+crowns.length+'   ❤️ '+player.health,20,30)}
const buttons=document.querySelectorAll('.touch-controls button');buttons.forEach(btn=>{const key=btn.dataset.key;const press=e=>{e.preventDefault();if(key==='jump'){touchJump.value=true}else keys[key]=true;btn.setPointerCapture?.(e.pointerId)};const release=e=>{e.preventDefault();if(key!=='jump')keys[key]=false};['pointerdown','touchstart'].forEach(ev=>btn.addEventListener(ev,press,{passive:false}));['pointerup','pointercancel','pointerleave','touchend'].forEach(ev=>btn.addEventListener(ev,release,{passive:false}))});
let last=performance.now();function loop(now){const dt=Math.min((now-last)/1000,.033);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);